parameters:
    memcached.data_collector.class: MentionMe\Bundle\MemcachedBundle\DataCollector\MemcachedDataCollector
    memcached.data_collector.template: MentionMeMemcachedBundle:DataCollector:memcached

services:
    data_collector.memcached:
        class: "%memcached.data_collector.class%"
        tags:
            - { name: data_collector, template: "%memcached.data_collector.template%", id: memcached }
